#edited by huiseong noh

SIM ?= icarus 
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES = $(shell pwd)/neuron02_LIF.v
MODULE = coco_bench 
TOPLEVEL = neuron02_LIF

include $(shell cocotb-config --makefiles)/Makefile.sim
